// JavaScript/impl-react/src/Components/controls/foundation.js
import React, { Component } from 'react';


export class Secret extends Component {
  render() {
    const {config} = this.props;
    return (
      <div>
        <label>
          {config.label}
          <input type="password" placeholder={config.placeholder} />
        </label>
      </div>
    );
  }
}

export class Toggle extends Component {
  render() {
    const {config} = this.props;
    return (
      <div>
        <input type="checkbox" />
        <label>{config.label}</label>
      </div>
    );
  }
}


export class Submit extends Component {
  render() {
    const {config} = this.props;
    return (
      <button type="submit" className="success button">{config.label}</button>
    );
  }
}


export class Email extends Component {
  render() {
    const {config} = this.props;
    return (
      <>
        <label>
          {config.label}
          <input type="email" className="form-control" placeholder={config.placeholder} />
        </label>
        <p className="help-text">{config.hint}</p>
      </>
    );
  }
}

// JavaScript/impl-angular/src/app/controls/foundation.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-email',
  template: `
    <label>
      {{ config.label }}
      <input type="email" class="form-control" [placeholder]="config.placeholder" />
    </label>
    <p class="help-text">{{ config.hint }}</p>
`})
export class EmailComponent {
  @Input() config: any;
}


@Component({
  selector: 'app-secret',
  template: `
    <label>
      {{ config.label }}
      <input type="password"  [placeholder]="config.placeholder">
    </label>
`})
export class SecretComponent {
  @Input() config: any;
}



@Component({
  selector: 'app-toggle',
  template: `
    <input type="checkbox">
    <label>{{ config.label }}</label>
`})
export class ToggleComponent {
  @Input() config: any;
}



@Component({
  selector: 'app-submit',
  template: `
    <button type="submit" class="success button">{{ config.label }}</button>
`})
export class SubmitComponent {
  @Input() config: any;
}
