// JavaScript/impl-react/src/Components/App.js
import React, { Component } from 'react';
import './App.css';
import { formConfig } from '../FormBuilder/formConfig.js';

export class App extends Component {
  render() {
    return (
      <div>
        <nav className="navbar navbar-light bg-light">
          <div className="navbar-brand">itenium</div>
        </nav>

        <div className="container">
          <form>
            <div className="form-group">
              <label>Email</label>
              <input type="email" className="form-control" />
            </div>
            <div className="form-group">
              <label>Password</label>
              <input type="password" className="form-control" />
            </div>
            <div className="form-group form-check">
              <input type="checkbox" className="form-check-input" />
              <label className="form-check-label">Remain logged in</label>
            </div>
            <button type="submit" className="btn btn-primary">Login</button>
          </form>
        </div>
      </div>
    );
  }
}

// JavaScript/impl-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { formConfig } from '../FormBuilder/formConfig';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  formConfig = formConfig;
}

<div>
  <nav class="navbar navbar-light bg-light">
    <div class="navbar-brand">itenium</div>
  </nav>

  <div class="container">
    <form>
      <div class="form-group">
        <label>Email</label>
        <input type="email" class="form-control" />
      </div>
      <div class="form-group">
        <label>Password</label>
        <input type="password" class="form-control" />
      </div>
      <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" />
        <label class="form-check-label">Remain logged in</label>
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</div>
